# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 753)
        MainWindow.setMaximumSize(QtCore.QSize(640, 860))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.txtEdit.setMaximumSize(QtCore.QSize(640, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.txtEdit.setFont(font)
        self.txtEdit.setObjectName("txtEdit")
        self.verticalLayout.addWidget(self.txtEdit)
        self.btnParse = QtWidgets.QPushButton(self.centralwidget)
        self.btnParse.setMinimumSize(QtCore.QSize(220, 60))
        self.btnParse.setMaximumSize(QtCore.QSize(220, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnParse.setFont(font)
        self.btnParse.setObjectName("btnParse")
        self.verticalLayout.addWidget(self.btnParse, 0, QtCore.Qt.AlignHCenter)
        self.txtInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtInfo.setMaximumSize(QtCore.QSize(640, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.txtInfo.setFont(font)
        self.txtInfo.setObjectName("txtInfo")
        self.verticalLayout.addWidget(self.txtInfo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Чтение данных из посылки SatDrive-TR"))
        self.btnParse.setText(_translate("MainWindow", "Расшифрование"))
